src/Entity/ProductVariantSpecificationInterface.php
<?php

declare(strict_types=1);

namespace DH\ArtisProductSpecificationPlugin\Entity;

use DH\Artis\Common\Entity\Product\ProductInterface;
use DH\Artis\Common\Entity\Product\ProductVariantInterface;
use DH\ArtisProductSpecificationPlugin\Entity\Translation\ProductVariantSpecificationTranslationInterface;
use Doctrine\Common\Collections\Collection;
use Sylius\Component\Resource\Model\ResourceInterface;
use Sylius\Component\Resource\Model\TimestampableInterface;
use Sylius\Component\Resource\Model\TranslatableInterface;
use Sylius\Component\Resource\Model\TranslationInterface;

interface ProductVariantSpecificationInterface extends
    ResourceInterface,
    TimestampableInterface,
    TranslatableInterface
{
    public function getCode(): ?string;

    public function setCode(?string $code): self;

    /**
     * @return ProductVariantSpecificationTranslationInterface|TranslationInterface
     */
    public function getTranslation(?string $locale = null): TranslationInterface;

    public function getVariant(): ?ProductVariantInterface;

    public function setVariant(?ProductVariantInterface $variant): self;

    public function getItems(): Collection;

    public function addItem(ProductVariantSpecificationItemInterface $item): void;

    public function removeItem(ProductVariantSpecificationItemInterface $item): void;

    public function hasItem(ProductVariantSpecificationItemInterface $item): bool;

    public function getDescription(): ?string;

    public function setDescription(?string $description): self;

    public function getName(): ?string;

    public function setName(?string $name): self;

    public function getProduct(): ?ProductInterface;

    public function setProduct(?ProductInterface $product): self;

    public function getItemConfigurations(): Collection;

    public function hasItemConfiguration(ProductVariantSpecificationItemConfigurationInterface $itemConfiguration): bool;

    public function addItemConfiguration(ProductVariantSpecificationItemConfigurationInterface $itemConfiguration): self;

    public function removeItemConfiguration(ProductVariantSpecificationItemConfigurationInterface $itemConfiguration): self;
}

src/Resources/views/Admin/Product/Tab/_specification.html.twig
{% from '@SyliusAdmin/Macro/translationForm.html.twig' import translationForm %}

{% block content %}
    {{ form_errors(form) }}

    <div class="ui tab" data-tab="specification">
        <h3 class="ui top attached header">{{ 'dh_artis_product_specification_plugin.ui.specification'|trans }}</h3>
        <div class="ui attached segment">
            {{ form_errors(form.specification) }}
            <div class="two fields">
                {{ form_row(form.specification.code) }}
            </div>
            {{ translationForm(form.specification.translations) }}
            <h4 class="ui dividing header">{{ 'dh_artis_product_specification_plugin.ui.product_variant_specification_items'|trans }}</h4>
            <div class="custom-title-bar">
                <div class="column">{{ 'dh_artis_product_specification_plugin.form.product_variant.specification.item_name'|trans }}</div>
                <div class="wrapper">
                    <div class="column">{{ 'dh_artis_product_specification_plugin.form.product_variant.specification.visible_in_description'|trans }}</div>
                    <div class="column">{{ 'dh_artis_product_specification_plugin.form.product_variant.specification.visible_in_product_list'|trans }}</div>
                    <div class="column">{{ 'dh_artis_product_specification_plugin.form.product_variant.specification.visible_in_description'|trans }}</div>
                    <div class="column">{{ 'dh_artis_product_specification_plugin.form.product_variant.specification.used_as_filter'|trans }}</div>
                </div>
            </div>
            <div class="option-values-container product-specification-parameters">
                {% if(form.specification.itemConfigurations is defined) %}
                    {{ form_row(form.specification.itemConfigurations) }}
                {% endif %}
            </div>
            <br>
        </div>
    </div>

    {% import '@SyliusUi/Macro/buttons.html.twig' as buttons %}

{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/dhartisproductspecificationplugin/css/product_specification_item_configuration.css') }}">
{% endblock %}